
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: planalto-indigo_development

test:
  <<: *default
  database: planalto-indigo_test

production:
  <<: *default
  database: planalto-indigo_production
  username: planalto-indigo
  password: <%= ENV['PLANALTO-INDIGO_DATABASE_PASSWORD'] %>
